import React, { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Sparkles, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { useTheme } from "next-themes";

interface AIPromptDialogProps {
  getExcalidrawAPI: () => any;
}

interface AINode {
  id: string;
  label: string;
  type?: string;
  tech?: string;
  color?: string;
  gridX?: number;
  gridY?: number;
}

interface AIEdge {
  from: string;
  to: string;
  label?: string;
}

interface AIDiagramData {
  nodes: AINode[];
  edges?: AIEdge[];
}

const createExcalidrawElement = (type: string, data: Partial<any>) => {
  return {
    id: `ai-${Math.random().toString(36).substr(2, 9)}`,
    type,
    x: 0,
    y: 0,
    width: 100,
    height: 100,
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "transparent",
    fillStyle: "hachure",
    strokeWidth: 1,
    strokeStyle: "solid",
    roughness: 1,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    seed: Math.floor(Math.random() * 100000),
    version: 1,
    versionNonce: Math.floor(Math.random() * 100000),
    isDeleted: false,
    boundElements: [],
    updated: Date.now(),
    link: null,
    locked: false,
    ...data,
  };
};

const wrapText = (text: string, maxChars: number) => {
  const words = text.split(" ");
  let lines = [];
  let currentLine = words[0];

  for (let i = 1; i < words.length; i++) {
    if (currentLine.length + words[i].length + 1 <= maxChars) {
      currentLine += " " + words[i];
    } else {
      lines.push(currentLine);
      currentLine = words[i];
    }
  }
  lines.push(currentLine);
  return lines.join("\n");
};

const AIPromptDialog = ({ getExcalidrawAPI }: AIPromptDialogProps) => {
  const { resolvedTheme } = useTheme();
  const [isOpen, setIsOpen] = useState(false);
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const fetchLogoDataUri = async (techSlug: string) => {
    try {
      const response = await fetch(`https://cdn.simpleicons.org/${techSlug}`);
      if (!response.ok) return null;
      const blob = await response.blob();
      return new Promise<string>((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.readAsDataURL(blob);
      });
    } catch (e) {
      return null;
    }
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    
    const excalidrawAPI = getExcalidrawAPI();
    if (!excalidrawAPI) {
      toast.error("Canvas is not ready yet.");
      return;
    }

    setIsGenerating(true);
    try {
      const res = await fetch("/api/generate-diagram", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt }),
      });

      const data: AIDiagramData = await res.json();
      if (!res.ok) throw new Error((data as any).error || "Failed to generate diagram");

      const { nodes, edges } = data;
      if (!nodes) throw new Error("No nodes generated by AI.");

      const isDark = resolvedTheme === "dark";
      const textColor = isDark ? "#ffffff" : "#1e1e1e"; 
      const boxColor = isDark ? "#ffffff" : "#1e1e1e";

      const elements: any[] = [];
      const nodeCoords = new Map<string, { x: number, y: number, w: number, h: number }>();
      const files: any[] = [];

      // Layout Constants
      const gridScaleX = 350;
      const gridScaleY = 220;
      const offsetX = 300;
      const offsetY = 300;
      const boxWidth = 140;
      const boxHeight = 140; 

      // 1. Process Nodes and Fetch Logos
      await Promise.all(nodes.map(async (node) => {
        const gridX = typeof node.gridX === 'number' ? node.gridX : 0;
        const gridY = typeof node.gridY === 'number' ? node.gridY : 0;
        const x = gridX * gridScaleX + offsetX;
        const y = gridY * gridScaleY + offsetY;
        
        nodeCoords.set(node.id, { x, y, w: boxWidth, h: boxHeight });

        // Fetch official logo
        let fileId = null;
        if (node.tech) {
          const dataUri = await fetchLogoDataUri(node.tech);
          if (dataUri) {
            fileId = `file-${node.tech}-${Math.random().toString(36).substr(2, 5)}`;
            files.push({
              id: fileId,
              dataURL: dataUri,
              mimeType: "image/svg+xml",
              created: Date.now(),
            });
          }
        }

        // Shape (Container)
        let shapeType = "rectangle";
        let roundness: any = { type: 3 };
        if (node.type === "database") {
          shapeType = "ellipse";
          roundness = null;
        }

        const container = createExcalidrawElement(shapeType, {
          x: x - boxWidth / 2,
          y,
          width: boxWidth,
          height: boxHeight,
          strokeColor: node.color || boxColor,
          backgroundColor: isDark ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.02)",
          roundness,
          strokeWidth: 2,
        });

        // Image (Logo)
        let imageElement = null;
        if (fileId) {
          imageElement = createExcalidrawElement("image", {
            x: x - 30, // Centered
            y: y + 20,
            width: 60,
            height: 60,
            fileId,
            status: "saved", // Mark as saved immediately
          });
        }


        // Text (Label)
        const textElement = createExcalidrawElement("text", {
          x: x - boxWidth / 2 + 10,
          y: y + (fileId ? 90 : 40),
          width: boxWidth - 20,
          text: wrapText(node.label, 15),
          fontSize: 14,
          fontFamily: 2,
          textAlign: "center",
          verticalAlign: "middle",
          strokeColor: isDark ? "#ffffff" : "#1e1e1e",
          containerId: container.id,
        });

        container.boundElements = [{ type: "text", id: textElement.id }];
        elements.push(container, textElement);
        if (imageElement) elements.push(imageElement);
      }));

      // 2. Add Files to Excalidraw
      if (files.length > 0) {
        excalidrawAPI.addFiles(files);
      }

      // 3. Create Edges
      edges?.forEach((edge) => {
        const from = nodeCoords.get(edge.from);
        const to = nodeCoords.get(edge.to);
        if (from && to) {
          const isHorizontal = Math.abs(to.x - from.x) > Math.abs(to.y - from.y);
          const startX = from.x + (isHorizontal ? (to.x > from.x ? boxWidth / 2 : -boxWidth / 2) : 0);
          const startY = from.y + (isHorizontal ? boxHeight / 2 : (to.y > from.y ? boxHeight : 0));
          const endX = to.x + (isHorizontal ? (to.x > from.x ? -boxWidth / 2 : boxWidth / 2) : 0);
          const endY = to.y + (isHorizontal ? boxHeight / 2 : (to.y > from.y ? 0 : boxHeight));

          const dx = endX - startX;
          const dy = endY - startY;

          const arrow = createExcalidrawElement("arrow", {
            x: startX,
            y: startY,
            points: isHorizontal 
              ? [[0, 0], [dx / 2, 0], [dx / 2, dy], [dx, dy]]
              : [[0, 0], [0, dy / 2], [dx, dy / 2], [dx, dy]],
            strokeColor: isDark ? "#555555" : "#cccccc",
            strokeWidth: 1,
          });

          if (edge.label) {
            const labelText = createExcalidrawElement("text", {
              x: startX + dx / 2 + 10,
              y: startY + dy / 2 - 10,
              text: edge.label,
              fontSize: 11,
              strokeColor: isDark ? "#aaaaaa" : "#666666",
            });
            elements.push(labelText);
          }
          elements.push(arrow);
        }
      });

      excalidrawAPI.updateScene({
        elements: [...excalidrawAPI.getSceneElements(), ...elements],
      });

      toast.success("Architectural Diagram Generated!");
      setIsOpen(false);
      setPrompt("");
    } catch (error: any) {
      console.error("AI Error:", error);
      toast.error(error.message);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <>
      <Button
        onClick={() => setIsOpen(true)}
        className="absolute bottom-10 right-10 z-50 rounded-full h-14 w-14 shadow-2xl bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white flex items-center justify-center transition-transform hover:scale-110 active:scale-95"
        title="Generate Diagram with AI"
      >
        <Sparkles size={24} />
      </Button>

      <Dialog open={isOpen} onOpenChange={setIsOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="text-blue-500" />
              Generate Diagram with AI
            </DialogTitle>
            <DialogDescription>
              Describe a process or workflow and AI will build the diagram for you.
            </DialogDescription>
          </DialogHeader>

          <div className="grid gap-4 py-4">
            <textarea
              className="min-h-[120px] w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 resize-none"
              placeholder="e.g. Create a flowchart for an ordering system..."
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
            />
          </div>

          <div className="flex justify-end gap-2">
            <Button variant="outline" onClick={() => setIsOpen(false)}>
              Cancel
            </Button>
            <Button 
              onClick={handleGenerate} 
              disabled={isGenerating || !prompt.trim()}
              className="bg-blue-600 hover:bg-blue-700 text-white"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating...
                </>
              ) : (
                "Generate"
              )}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default AIPromptDialog;
